linters-settings:
  govet:
    check-shadowing: true
  misspell:
    locale: US

linters:
  enable-all: true
  disable:
    - maligned
    - lll
    - funlen
    - govet
    - stylecheck
    - godox
    - wsl
    - errcheck
    - gosec
    - whitespace
    - gocognit
    - gochecknoglobals
    - scopelint
    - prealloc

issues:
  exclude-use-default: false

run:
  skip-dirs-use-default: false
